
export const projects = [
    {
        title: "Forklift Battery Conversion",
        location: "Ceylon Tobacco Company PLC",
        capacity: "15kW",
        image: "/projects/Forklift Battery Conversion.jpg?height=300&width=500",
        description: "Upgrading industrial forklifts for greener logistics.",
        year: "2024",
        client: "Johnson Family",
        duration: "3 days",
        savings: "$2,400/year",
        co2Reduction: "12 tons/year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
    },
    {
        title: "Electric Three-Wheeler Conversion",
        location: "Laugfs Eco Sri",
        capacity: "2.5MW",
        image: "/projects/Electric Three-Wheeler Conversion.jpg?height=300&width=500",
        description: " Electrifying urban mobility with custom lithium tech.",
        year: "2023",
        client: "Phoenix Industries",
        duration: "10 days",
        savings: "$50,000/year",
        co2Reduction: "50 tons/year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
    },
    {
        title: "Electric Vehicle Conversion",
        location: "Jinasena Innovation & Technology Institute (Pvt) Ltd",
        capacity: "5MW",
        image: "/projects/Electric Vehicle Conversion.jpg?height=300&width=500",
        description: "Pioneering EV adoption through smart battery solutions.",
        year: "2023",
        client: "Austin Solar Coop",
        duration: "15 days",
        savings: "$100,000/year",
        co2Reduction: "100 tons/year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
    },
    {
        title: "Supply Energy Solutions",
        location: "Orel Corporation & Ferentino Tyre Corporation",
        capacity: "10MWh",
        image: "/projects/Supply Energy Solutions.jpg?height=300&width=500",
        description: "Industry-grade energy storage for peak performance.",
        year: "2024",
        client: "Denver Grid Solutions",
        duration: "20 days",
        savings: "$200,000/year",
        co2Reduction: "200 tons/year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
    },
    {
        title: "On Grid Solar Projects",
        location: "Portland, OR",
        capacity: "500kW",
        image: "/projects/On Grid Solar Projects.jpg?height=300&width=500",
        description:
            "Smart solar systems to cut energy costs, not corners.",
        year: "2023",
        client: "Portland School District",
        duration: "7 days",
        savings: "$15,000/year",
        co2Reduction: "15 tons/year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
    },
    {
        title: "Off Grid Solar Projects",
        location: "Fresno, CA",
        capacity: "1.2MW",
        image: "/projects/Off Grid Solar Projects.jpg?height=300&width=500",
        description: "Reliable solar independence for remote and rugged sites.",
        year: "2024",
        client: "Fresno AgriTech",
        duration: "12 days",
        savings: "$30,000/year",
        co2Reduction: "30 tons/year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
    },
]

export const projectPhases = [
    {
        phase: "Site Assessment",
        description: "Comprehensive evaluation of solar potential and structural requirements",
    },
    { phase: "System Design", description: "Custom engineering design optimized for maximum energy production" },
    { phase: "Permitting", description: "Handling all necessary permits and utility interconnection agreements" },
    { phase: "Installation", description: "Professional installation by certified technicians" },
    { phase: "Commissioning", description: "System testing, monitoring setup, and performance verification" },
    { phase: "Maintenance", description: "Ongoing monitoring and maintenance support" },
]
