import { X, MapPin, Zap, Calendar, Users, DollarSign, Leaf } from "lucide-react"
export const projects = [
    {
        title: "Forklift Battery Conversion",
        location: "Ceylon Tobacco Company PLC",
        capacity: "15kW",
        image: "/placeholder.svg?height=300&width=500",
        description: "We spearheaded the conversion of their electric forklift batteries from lead acid to advanced lithium battery packs.",
        year: "2024",
        client: "Johnson Family",
        duration: "3 days",
        savings: "$2,400/year",
        co2Reduction: "12 tons/year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
    },
    {
        title: "Electric Three-Wheeler Conversion",
        location: "Laugfs Eco Sri",
        capacity: "2.5MW",
        image: "/placeholder.svg?height=300&width=500",
        description: "We played a pivotal role by designing and supplying cutting-edge lithium battery packs tailored to their specific requirements.",
        year: "2023",
        client: "Phoenix Industries",
        duration: "10 days",
        savings: "$50,000/year",
        co2Reduction: "50 tons/year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
    },
    {
        title: "Electric Vehicle Conversion",
        location: "Jinasena Innovation & Technology Institute (Pvt) Ltd",
        capacity: "5MW",
        image: "/placeholder.svg?height=300&width=500",
        description: "We enabled accelerate the adoption of electric mobility solutions across various applications.",
        year: "2023",
        client: "Austin Solar Coop",
        duration: "15 days",
        savings: "$100,000/year",
        co2Reduction: "100 tons/year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
    },
    {
        title: "Supply Energy Solutions",
        location: "Orel Corporation & Ferentino Tyre Corporation",
        capacity: "10MWh",
        image: "/placeholder.svg?height=300&width=500",
        description: "Our commitment to delivering high-quality energy storage solutions that meet the demanding needs of various sectors.",
        year: "2024",
        client: "Denver Grid Solutions",
        duration: "20 days",
        savings: "$200,000/year",
        co2Reduction: "200 tons/year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
    },
    {
        title: "On Grid Solar Projects",
        location: "Portland, OR",
        capacity: "500kW",
        image: "/placeholder.svg?height=300&width=500",
        description:
            "We specialize in providing trusted and reliable on-grid solar solutions to maximize energy efficiency & reduce electricity costs.",
        year: "2023",
        client: "Portland School District",
        duration: "7 days",
        savings: "$15,000/year",
        co2Reduction: "15 tons/year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
    },
    {
        title: "Off Grid Solar Projects",
        location: "Fresno, CA",
        capacity: "1.2MW",
        image: "/placeholder.svg?height=300&width=500",
        description: "We provide reliable off-grid solar solutions for remote areas using our in-house lithium battery packs.",
        year: "2024",
        client: "Fresno AgriTech",
        duration: "12 days",
        savings: "$30,000/year",
        co2Reduction: "30 tons/year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
    },
]

export const projectPhases = [
    {
        phase: "Site Assessment",
        description: "Comprehensive evaluation of solar potential and structural requirements",
    },
    { phase: "System Design", description: "Custom engineering design optimized for maximum energy production" },
    { phase: "Permitting", description: "Handling all necessary permits and utility interconnection agreements" },
    { phase: "Installation", description: "Professional installation by certified technicians" },
    { phase: "Commissioning", description: "System testing, monitoring setup, and performance verification" },
    { phase: "Maintenance", description: "Ongoing monitoring and maintenance support" },
]
