
export const projects = [
    {
        title: "Forklift Battery Conversion",
        location: "Ceylon Tobacco Company PLC",
        capacity: "",
        image: "/projects/Forklift Battery Conversion.jpg?height=300&width=500",
        description: "Upgrading industrial forklifts for greener logistics.",
        year: "2020",
        client: "CTC, GRI, Norochchole, DeSo",
        NoofConversionsDone: "25+",
        BatteryLifespan:"10+ Years",
        Maintenance:"Zero Maintenance",
        ChargingTime:"Reduced by 50%",
        RunTime:"Increased by 60%",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
        cb1:"Achieved higher operational efficiency with faster charging and longer run times.",
        cb2:"Reduced maintenance costs compared to lead-acid batteries.",
        cb3:"Increased fleet uptime and reliability in daily operations.",
        cb4:"Delivered long-term cost savings through extended battery lifespan.",
        description2: "We partnered with Ceylon Tobacco Company to upgrade their electric forklift fleet by replacing outdated lead-acid batteries with advanced lithium battery packs. This project boosted operational efficiency, reduced downtime, and delivered long-term cost savings through durability and low maintenance. It stands as a showcase of our expertise in industrial battery conversions for sustainable logistics."
    },
    {
        title: "Electric Three-Wheeler Conversion",
        location: "Laugfs Eco Sri",
        capacity: "8kWh",
        image: "/projects/Electric Three-Wheeler Conversion.jpg?height=300&width=500",
        description: " Electrifying urban mobility with custom lithium tech.",
        year: "2023",
        client: "Laugfs Eco Sri",
        Range: "120km +",
        co2Reduction: "0.2kg /km",
        TreesEquivalent: "337 per year",
        SavingOnFuel: "0.5M / year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
        cb1:"Enabled cleaner, greener transportation with reduced carbon emissions.",
        cb2:"Lowered fuel and operational costs through lithium battery technology.",
        cb3:"Improved vehicle reliability and range, making EV adoption easier.",
        cb4:"Supported sustainable mobility goals in urban transport.",
        description2: "In collaboration with Laugfs Eco Sri, we powered their electric three-wheeler initiative with custom-built lithium battery solutions. Our technology improved performance, reliability, and range while cutting down emissions and operational costs. This project highlights our role in supporting green transportation solutions in Sri Lanka’s urban mobility sector."
    },
    {
        title: "Electric Vehicle Conversion",
        location: "Jinasena Innovation & Technology Institute (Pvt) Ltd",
        capacity: "15kWh",
        image: "/projects/Electric Vehicle Conversion.jpg?height=300&width=500",
        description: "Pioneering EV adoption through smart battery solutions.",
        year: "2023",
        client: "Jinasena Innovation & Technology Institute (Pvt) Ltd",
        Range: "120km +",
        co2Reduction: "0.2kg /km",
        TreesEquivalent: "337 per year",
        SavingOnFuel: "0.5M / year",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
        cb1:"Enhanced vehicle efficiency and range with customized lithium batteries.",
        cb2:"Provided reliable performance across multiple conversion projects.",
        cb3:"Accelerated R&D and adoption of EV technology in Sri Lanka.",
        cb4:"Strengthened Jinasena’s position as a pioneer in innovation.",
        description2: "We worked with Jinasena Innovation & Technology Institute to supply high-performance lithium batteries for their EV conversion projects. Our solutions delivered superior range, efficiency, and reliability, accelerating the adoption of sustainable electric mobility across different applications."
    },
    {
        title: "Supply Energy Solutions",
        location: "Orel Corporation & Ferentino Tyre Corporation",
        capacity: "500kWh",
        image: "/projects/Supply Energy Solutions.jpg?height=300&width=500",
        description: "Industry-grade energy storage for peak performance.",
        year: "2024",
        client: "OREL Corporation & Ferentino Tyre Corporation",
        duration: "6 months",
        savings: "20% reduction in energy expenses",
        category: "Industrial Energy Storage",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
        cb1:"Secured dependable energy storage for large-scale industrial use.",
        cb2:"Improved operational efficiency with reduced downtime.",
        cb3:"Advanced sustainability efforts by integrating clean energy.",
        cb4:"Ensured long-term cost effectiveness with durable lithium packs.",
        description2: "Our lithium battery packs power operations at OREL Corporation and Ferentino Tyre Corporation, helping them achieve energy efficiency and sustainability goals. These collaborations prove our ability to deliver scalable, industry-grade energy storage systems for leading businesses in Sri Lanka."
    },
    {
        title: "On Grid Solar Projects",
        location: "",
        capacity: "5kW+",
        image: "/projects/On Grid Solar Projects.jpg?height=300&width=500",
        description:
            "Smart solar systems to cut energy costs, not corners.",
        year: "2023",
        client: "Homes & Businesses",
        duration: "2–4 months",
        savings: "up to 40–60% reduction in utility bills",
        category: "On-Grid Solar Power Systems",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
        cb1:"Delivered reduced electricity bills through optimized solar integration.",
        cb2:"Ensured seamless performance with grid-connected reliability.",
        cb3:"Supported long-term savings and energy independence.",
        cb4:"Enhanced property value with sustainable solar systems.",
        description2: "We deliver grid-connected solar power systems designed for maximum energy efficiency and reduced utility bills. Our expert installations ensure long-term reliability, empowering homes and businesses to generate clean renewable energy while staying grid-connected."
    },
    {
        title: "Off Grid Solar Projects",
        location: "",
        capacity: "5kW+",
        image: "/projects/Off Grid Solar Projects.jpg?height=300&width=500",
        description: "Reliable solar independence for remote and rugged sites.",
        year: "2024",
        client: "Rural communities, industrial facilities",
        duration: "3–6 months",
        savings: "elimination of diesel generator costs",
        category: "On-Grid Solar Power Systems",
        stats: { vessels: "25", range: "100nm", weight: "-50%", efficiency: "98%" },
        cb1:"Provided reliable energy access in areas with no or unstable grid.",
        cb2:"Ensured independent, continuous power for rural, industrial, and emergency use.",
        cb3:"Increased resilience and reliability with in-house lithium storage.",
        cb4:"Supported sustainability goals with clean renewable energy.",
        description2: "For remote or grid-limited locations, we offer off-grid solar solutions with in-house developed lithium battery packs. These systems ensure continuous, independent power supply with durability and efficiency, making them ideal for rural, industrial, and emergency energy needs."
    },
]

// export const projectStats = [
//     { icon: Zap, label: "System Capacity", value: capacity },
//     { icon: Calendar, label: "Project duration", value: year },
//     { icon: Users, label: "O2 reduction", value: duration },
//     { icon: DollarSign, label: "Compilation year", value: savings },
//     { icon: Leaf, label: "Annual saving", value: co2Reduction },
//     { icon: MapPin, label: "Location", value: location },
// ]

export const projectPhases = [
    {
        phase: "Site Assessment",
        description: "Comprehensive evaluation of solar potential and structural requirements",
    },
    { phase: "System Design", description: "Custom engineering design optimized for maximum energy production" },
    { phase: "Permitting", description: "Handling all necessary permits and utility interconnection agreements" },
    { phase: "Installation", description: "Professional installation by certified technicians" },
    { phase: "Commissioning", description: "System testing, monitoring setup, and performance verification" },
    { phase: "Maintenance", description: "Ongoing monitoring and maintenance support" },
]
